ServerName localhost

<Directory /var/www/html>
    AllowOverride All
    Require all granted
</Directory>

LoadModule rewrite_module modules/mod_rewrite.so

RewriteEngine On

# Force www
RewriteCond %{HTTP_HOST} ^sadhuvandna\.co\.in$ [NC]
RewriteRule ^(.*)$ https://www.sadhuvandna.co.in/$1 [L,R=301]

# Custom routes
RewriteRule ^restaurant/([a-zA-Z0-9_-]+)/?$ user/menu.php?slug=$1 [L,QSA]
RewriteRule ^order/([A-Za-z0-9]+)/?$ user/order.php?track=$1 [L,QSA]

# Remove .php extension
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME}.php -f
RewriteRule ^([^/]+)/?$ $1.php [L]
